### ISSUE TITLE
Visual issues

### ISSUE THREAD

**Issue by mzgreen** [frogermcs/AndroidDevMetrics#1]
As you can see something is wrong with styles. Also I'm not sure but measuring doesn't seem to work good either.

Tested on Android 4.4.2 and 5.0.1. Result is the same on both devices.

![screenshot_2016-02-01-13-00-07](https://cloud.githubusercontent.com/assets/6561747/12716880/1e897e86-c8e4-11e5-9fdd-a4f69866a9a7.png)

**Comment by frogermcs** [comment]
0ms could mean that all needed dependencies are already initialized and are taken from dependencies graph (what is much less than 1ms).

This activity shows only those dependencies which are initialized from scratch (@Inject annotated constructor or provide method from module is called).

Style will be fixed.

**Comment by mzgreen** [comment]
I see. One more question btw. Does it analyze whole graph? I mean, will subcomponents/component dependencies be analyzed?

**Comment by frogermcs** [comment]
It should drill down whole requested dependencies graph recursively. Still, not components are analyzed but constructors and provide methods. 

...but currently it could have some problems with named injections and interfaces. Still under development. ;)

**Comment by mzgreen** [comment]
Keep up great work :+1:

**Comment by frogermcs** [comment]
styling fixed
