### ISSUE TITLE
Import doesn't work with beta build type

### ISSUE THREAD

**Issue by sealskej** [frogermcs/AndroidDevMetrics#15]
I have beta build type defined in `build.gradle` file with the same settings as debug build type. When I want to build this beta build (`./gradlew assembleBeta`) I get the error message with missing import `com.frogermcs.androiddevmetrics.AndroidDevMetrics`. Debug and release build types work properly.

**Comment by williamwebb** [comment]
The plugin will only automatically add imports for the debug and release sourcesets. Assuming you don't want the functionality for your beta build type for a temp fix you can just add the noop dependency to your betaComplile.

``` java
betaCompile 'com.frogermcs.androiddevmetrics:androiddevmetrics-runtime-noop:0.3.1'
```

**Comment by sealskej** [comment]
Works well. Thank you!
