### ISSUE TITLE
Update Android dependencies

### ISSUE THREAD

**Issue by skrzyneckik** [frogermcs/AndroidDevMetrics#42]
There were no major updates to this library for quite some time, so I would like to propose to update its Android dependencies to the newest version - build tools (27.0.3) and support libraries (27.0.2). It would be a good first step towards supporting Android API 26+ (#38). The first tiny step has been already taken in #41

**Comment by frogermcs** [comment]
Updated in v0.6

**Comment by skrzyneckik** [comment]
@frogermcs, after your tweet I thought you're busy and I was working on it right now. Good I didn't spend too much time on it ;)
