### ISSUE TITLE
`Building AndroidDevMetrics` section to make it easier for new contributors to start

### ISSUE THREAD

**Issue by skrzyneckik** [frogermcs/AndroidDevMetrics#43]
When I've checked this project source code for the first time I found it difficult to build this plugin and check its behaviour in my project. I would like to add `Building AndroidDevMetrics` with a few steps of description how to start.

@frogermcs what do you think?

**Comment by frogermcs** [comment]
I assumed that project will be used mostly as a compiled library. But hey, if you find it useful, why not. :)

**Comment by skrzyneckik** [comment]
After #47 has been merged there is nothing to do here
