### ISSUE TITLE
Convert `AndroidDevMetricsPlugin` Groovy to Java/Kotlin

### ISSUE THREAD

**Issue by skrzyneckik** [frogermcs/AndroidDevMetrics#44]
`AndroidDevMetrics` plugin is mainly used by Android/Java developer. I would like to convert existing Groovy to language known by plugin's users and potential developers. 

I think it isn't about understanding what e.g `AndroidDevMetricsPlugin.groovy` does, but to make it easier to modify existing code.

@frogermcs what do you think?

**Comment by frogermcs** [comment]
Actually almost entire groovy code is just copy and paste from other open source projects. When I was writing this library I focused mostly on runtime part of it.
 If you think it can be helpful with further development I'm more than happy to improve quality of this part of project. :)

**Comment by skrzyneckik** [comment]
Applied by #46
