### ISSUE TITLE
when i run on non marshmallow it always crashes.

### ISSUE THREAD

**Issue by j2emanue** [frogermcs/AndroidDevMetrics#5]
When i subclass Application and do this configuration in gradle :

```
android {
    compileSdkVersion 23
    buildToolsVersion "23.0.2"

    defaultConfig {
        applicationId "com.example.uen229.mydagger2application"
        minSdkVersion 16
        targetSdkVersion 23
        versionCode 1
        versionName "1.0"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

```

```
dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    testCompile 'junit:junit:4.12'
    compile 'com.android.support:appcompat-v7:23.1.1'
    compile 'com.google.dagger:dagger:2.0'
    apt 'com.google.dagger:dagger-compiler:2.0'
    provided 'org.glassfish:javax.annotation:10.0-b28'
}
```

dagger2metrics make the app crash with :

> FATAL EXCEPTION: main
>                                                                                        java.lang.VerifyError: com/example/uen229/mydagger2application/butters/ButterModule$AjcClosure1
>                                                                                            at com.example.uen229.mydagger2application.butters.ButterModule.ProvideCashewButter(ButterModule.java:23)
>                                                                                            at com.example.uen229.mydagger2application.butters.ButterModule_ProvideCashewButterFactory.get(ButterModule_ProvideCashewButterFactory.java:17)
>                                                                                            at com.example.uen229.mydagger2application.butters.ButterModule_ProvideCashewButterFactory.get(ButterModule_ProvideCashewButterFactory.java:6)
>                                                                                            at com.example.uen229.mydagger2application.component.DaggerButterComponent.ProvideCashewButter(DaggerButterComponent.java:32)
>                                                                                            at com.example.uen229.mydagger2application.component.DaggerSandwichComponent$1.get(DaggerSandwichComponent.java:37)
>                                                                                            at com.example.uen229.mydagger2application.component.DaggerSandwichComponent$1.get(DaggerSandwichComponent.java:35)
>                                                                                            at com.example.uen229.mydagger2application.Sandwitches.SandwichModule_ProvidesCashewSandwitchFactory.get(SandwichModule_ProvidesCashewSandwitchFactory.java:22)
>                                                                                            at com.example.uen229.mydagger2application.Sandwitches.SandwichModule_ProvidesCashewSandwitchFactory.get(SandwichModule_ProvidesCashewSandwitchFactory.java:8)
>                                                                                            at dagger.internal.ScopedProvider.get(ScopedProvider.java:46)
>                                                                                            at com.example.uen229.mydagger2application.MainActivity_MembersInjector.injectMembers(MainActivity_MembersInjector.java:31)
>                                                                                            at com.example.uen229.mydagger2application.MainActivity_MembersInjector.injectMembers(MainActivity_MembersInjector.java:10)
>                                                                                            at com.example.uen229.mydagger2application.component.DaggerSandwichComponent.inject(DaggerSandwichComponent.java:56)
>                                                                                            at com.example.uen229.mydagger2application.MainActivity.onCreate(MainActivity.java:52)
>                                                                                            at android.app.Activity.performCreate(Activity.java:5008)
>                                                                                            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1079)
>                                                                                            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2023)
>                                                                                            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2084)
>                                                                                            at android.app.ActivityThread.access$600(ActivityThread.java:130)
>                                                                                            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1195)
>                                                                                            at android.os.Handler.dispatchMessage(Handler.java:99)

My trivial project is here: https://github.com/j2emanue/dagger2_scope_demo.git

if you just download it and run as is it works, but when i add dagger2metrics it fails.

**Comment by frogermcs** [comment]
Cannot reproduce on your example - everything seems working. Could you try to update gradle plugin (I've tested on: `com.android.tools.build:gradle:2.0.0-alpha6`). 

Also could you post your Application class code?

**Comment by j2emanue** [comment]
my application subclass works fine.  I changed it to alpha6 as you suggested and it started working.  FYI, when  i toggle between using com.android.tools.build:gradle:2.0.0-alpha9 and alpha6 the issue arises in alpha9.  What i did was switched alphas then did a 'rebuild project' every time.  Anyway this is satisfactory for me and plus these are alpha builds.  Thanks for the help.
