### ISSUE TITLE
gradle assembleRelease fails.

### ISSUE THREAD

**Issue by himanshuvirmani** [frogermcs/AndroidDevMetrics#6]
assembleDebug is working fine when dagger2metrics is added but assembleRelease fails with the following error. Is there a way we can keep the code and make sure release build works fine.

error: package com.frogermcs.dagger2metrics does not exist
import com.frogermcs.dagger2metrics.Dagger2Metrics;
                                   ^
1 error
:app:compileReleaseJavaWithJavac FAILED

**Comment by Plastix** [comment]
I am getting this error as well.
